# Blue Print deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec: 
  replicas: 1 
  # which pods belong to the deployment labels
  selector: 
    matchLabels: 
      app: webapp
  template:
    metadata: 
      labels:
        app: webapp
    spec: 
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        # Username & password for DB FROM > Secret 
        env: 
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: USER_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
---
# Part 2 - Service for exposing the requests to the mogo service
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec: 
  type: NodePort
  selector: 
    app: webapp
  ports: 
    - protocol: TCP
      port: 8080
      targetPort: 3000
      nodePort: 30100